//+------------------------------------------------------------------+
//|                                                StockGeniusXAU.mq5 |
//|                      Generated by ChatGPT - MQL5 Expert Advisor  |
//+------------------------------------------------------------------+
#property copyright ""
#property link      ""
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>

CTrade trade;

int fast_ma_handle = INVALID_HANDLE;
int slow_ma_handle = INVALID_HANDLE;

input group "Paramètres de la Stratégie";
input int               Fast_MA_Period = 10;
input int               Slow_MA_Period = 30;
input ENUM_MA_METHOD    MA_Method      = MODE_EMA;
input ENUM_APPLIED_PRICE MA_Price      = PRICE_CLOSE;

input group "Gestion des Ordres";
input int    Stop_Loss_Pips   = 200;
input int    Take_Profit_Pips = 400;
input long   Magic_Number     = 2024001;

input group "Gestion du Risque";
input double Risk_Percent = 1.0;

int OnInit()
  {
   trade.SetExpertMagicNumber(Magic_Number);

   ResetLastError();
   fast_ma_handle = iMA(_Symbol,_Period,Fast_MA_Period,0,MA_Method,MA_Price);
   if(fast_ma_handle == INVALID_HANDLE)
     {
      PrintFormat("Erreur lors de la création de la moyenne mobile rapide (période %d). Code d'erreur : %d", Fast_MA_Period, GetLastError());
      return(INIT_FAILED);
     }

   ResetLastError();
   slow_ma_handle = iMA(_Symbol,_Period,Slow_MA_Period,0,MA_Method,MA_Price);
   if(slow_ma_handle == INVALID_HANDLE)
     {
      PrintFormat("Erreur lors de la création de la moyenne mobile lente (période %d). Code d'erreur : %d", Slow_MA_Period, GetLastError());
      return(INIT_FAILED);
     }

   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
  }

void OnTick()
  {
  }
