name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installer les dépendances
        run: |
          python -m pip install -r requirements-dev.txt
          python -m pip install .
      - name: Exécuter les tests
        run: pytest --cov=src --cov-report=xml
      - name: Publier sur Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
          minimum_coverage: 80
